services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__sqlConnection=Server=sqlserver;Database=bakery;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
     - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/lib/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "1455:1433"



volumes:
  sqlserver_data: