services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4404:80"
    depends_on:
     - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: bakery
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"


volumes:
  mysql-data: